#!/usr/bin/env ruby

require "httparty"
require "nokogiri"
require "rainbow"
require "ostruct"

def show_latest
  begin
    response = HTTParty.get("http://news.ycombinator.com")
  rescue
    puts "fix yo internets"
  end
  if !response || response.body == @previous_body
    return
  end
  @previous_body = response.body

  html = Nokogiri::HTML(response.body)
  items = []
  html.css("td.title a").each do |node|
    unless node.text == "More"
      items << OpenStruct.new(points: node.parent.parent.next_sibling.css("span").text, title: node.text, url: node["href"])
    end
    break if items.size == 15
  end 

  puts "\e[H\e[2J"

  max_width = items.map {|i|
    ["#{i.title} #{i.points}".size, i.url.size]
  }.flatten.max

  puts Rainbow("Hacker News").ljust(max_width).background("#ff6600").foreground(:black)
  items.each do |item|
      title = Rainbow(item.title + " ").background("#f6f6ef").color(:black)
      points = Rainbow("(#{item.points})").rjust(max_width - item.title.size - 1).background("#f6f6ef").color(:red)
      puts Rainbow("#{title}#{points}")
      puts Rainbow(item.url).ljust(max_width).background("#f6f6ef").color(:blue)
    end
end

loop {
  show_latest
  sleep 60
}
